name: perfectionist-dfd CI

on:
  push:
    branches:
      - master
      - main
      - feature**
      - staging**
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:ci
    - run: mkdir packdir && npm pack --pack-destination packdir
      if: matrix.node-version == '16.x'
    - name: Upload package as artifact
      if: matrix.node-version == '16.x'
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: perfectionist-dfd-${{ matrix.node-version }}.tgz
        path: packdir/*
        retention-days: 1
